version: '3'

services:

  nginx:
    image: nginx:1.11-alpine
    ports:
    - 80
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/app
    depends_on:
    - php

  php:
    image: jorge07/alpine-php:7.2-dev-sf
    volumes:
    - .:/app