version: '3'

services:

  nginx:
    image: nginx:1.11-alpine
    ports:
    - 80
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/app
    environment:
    - VIRTUAL_HOST=showme.loc
    depends_on:
    - php

  php:
    build:
      context: ./docker/php
    expose:
    - 9000
    volumes:
    - .:/app


  reverse-proxy:
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro